### ISSUE TITLE
Can't post free text invoice

### ISSUE THREAD

**Issue by AMorin8787** [MicrosoftLearning/MB-920T00A-Microsoft-Dynamics-365-Fundamentals-Finance-and-Operations-Apps#10]
# Module: 02
#### Step: 05

When trying to post the free text invoice, errors are received saying "There has been an error in fiscal period validation in company usmf". Trying to adjust the date give another error stating the main account cannot process debit transactions. 

Workaround has been to change the "DB/CR default" and "DB/CR requirement" to "Credit" instead of "Debit" in Module 2 Lab 1 Step 5. And then in Module 2 Lab 2 Step 5, changing the invoice dates to "1/10/2022" and "1/20/2022" before posting the invoice.

![image](https://user-images.githubusercontent.com/48496971/211602540-0f5d6445-7b70-414d-bae1-dcfc1d4306e5.png)

**Comment by ephiax20** [comment]
@CeleneA I was able to replicate this issue in testing.  I found changing just the **Invoice Date** and **Due** values to last year was enough to work around it.

**Comment by CeleneA** [comment]
Thank you Simon!

Celene Abramson (she/her)
Sr. Content Developer
Cell Phone: 425.681.2006
***@***.******@***.***>

[Microsoft]
﻿ One Microsoft Way, Redmond, WA 98052 USA

**Comment by CeleneA** [comment]
This issue has been fixed.

**Comment by CeleneA** [comment]
Apologies - I jumped the gun. To be addressed shortly.
