### ISSUE TITLE
Lab 1.1 Screenshots

### ISSUE THREAD

**Issue by julians1966** [MicrosoftLearning/MB-920T00A-Microsoft-Dynamics-365-Fundamentals-Finance-and-Operations-Apps#34]
# Module: 1
#### Step: 9 and 19 and 20

Description of issue

Screenshots are in the wrong place in the lab steps

Repro steps:

1. Step 9 the screenshot should probably be for step 19
1. Step 10 screenshot should probably be for step 3
1. Step 20 is unclear for students and wound benefit from a screenshot to show where to find Related information

**Comment by a-ainamdar** [comment]
Thank you for raising this issue. Currently, we are reviewing this. 
We will keep you posted.
