### ISSUE TITLE
Fiscal calendar dates

### ISSUE THREAD

**Issue by julians1966** [MicrosoftLearning/MB-920T00A-Microsoft-Dynamics-365-Fundamentals-Finance-and-Operations-Apps#35]
# Module: 2
#### Step: 2

Description of issue

The start and end date only create 3 periods

Should be Start date: 10/1/2024 and End Date 9/30/2025

**Comment by a-ainamdar** [comment]
Thank you for raising this issue. Currently, we are reviewing this. 
We will keep you posted.
