### ISSUE TITLE
Main expense type

### ISSUE THREAD

**Issue by julians1966** [MicrosoftLearning/MB-920T00A-Microsoft-Dynamics-365-Fundamentals-Finance-and-Operations-Apps#36]
# Module: 2
#### Step: 3 and 4 and 5

Description of issue

Incorrect field name

Step says 
Main expense type: Balance sheet

Should say
Main account type: Balance sheet

**Comment by a-ainamdar** [comment]
Thank you for raising this issue. Currently, we are reviewing this and will keep you posted
