### ISSUE TITLE
Ledger setup

### ISSUE THREAD

**Issue by julians1966** [MicrosoftLearning/MB-920T00A-Microsoft-Dynamics-365-Fundamentals-Finance-and-Operations-Apps#38]
# Module: 2
#### Step: 3

Description of issue
Incorrect navigation to Ledger page

Navigation should be 
Modules > General ledger > Ledger setup > Ledger

**Comment by a-ainamdar** [comment]
Thank you for raising this issue. Currently, we are reviewing this and will keep you posted
