### ISSUE TITLE
Lab 3.1 Switch to USMF to show Released products

### ISSUE THREAD

**Issue by julians1966** [MicrosoftLearning/MB-920T00A-Microsoft-Dynamics-365-Fundamentals-Finance-and-Operations-Apps#39]
# Module: 3
#### Step: 33

Description of issue

Need to switch to USMF as the Legal Entity will be CDS, otherwise there are no released products lists

**Comment by a-ainamdar** [comment]
Thank you for raising this issue. Currently, we are reviewing this and will keep you posted
