### ISSUE TITLE
Accounts Payable and Account Receivable missing in environment!

### ISSUE THREAD

**Issue by QAJaneHowell** [MicrosoftLearning/MB-920T00A-Microsoft-Dynamics-365-Fundamentals-Finance-and-Operations-Apps#4]
# Module: 02
#### Step: 03

Description of issue
Step asks learners to navigate to the Accounts Payable Module > Payments  > Vendor Payment Journal. 
This module, along with Accounts Receivable is missing from the environment!
I am not sure how these two modules can be missing as they are major components of the Finance area, but they are just not there.
I have refreshed the environment, logged back onto the Environment etc, but they are still missing.

When I search directly for Vendor Payment Journal, that is also missing. 
Repro steps:
![image](https://user-images.githubusercontent.com/59439005/136409093-044f1ab0-2c48-41b5-8720-fe7a3e7fa012.png)
![image](https://user-images.githubusercontent.com/59439005/136409222-58e976bd-9ac4-4984-a3be-28a5e0b3a05b.png)

**Comment by CeleneA** [comment]
Jane - were you using LODS again?

**Comment by QAJaneHowell** [comment]
Yes Celene - I do not know why the image is so wrong, but there are so many modules missing from it.

**Comment by QAJaneHowell** [comment]
I have submitted a support ticket directly with LOD for this issue and for the missing Inventory Management module too.
