### ISSUE TITLE
Lab 1.2: Excel integration - Add-in Failed to retrieve server config

### ISSUE THREAD

**Issue by HashirSajjad** [MicrosoftLearning/MB-920T00A-Microsoft-Dynamics-365-Fundamentals-Finance-and-Operations-Apps#41]
# Module: M01
#### Step: 5

Description of issue:
As soon as the downloaded excel is opened. The MS Office Dynamics Add-in shows the error below. It does not ask to sign-in anywhere, there is just this error.

![image](https://github.com/user-attachments/assets/8ad5cdbb-05be-4c17-8c37-e1ce4ee43643)

**Comment by a-ainamdar** [comment]
Hi,
Thank you for raising this issue. We will review this and update you soon.

**Comment by a-ainamdar** [comment]
Hi Hashir,

I am using Skillable and I am not able to reproduce this issue. 
Can you please let me know if you are still able to reproduce the issue? If So then can you please further assist with details of lab you are using?

**Comment by HashirSajjad** [comment]
Hi,

I am using labs from Xtremelabs. I have encountered another issue while performing the lab which is restricting me to reach the point where the original issue occurs.

Currently when I go to my browser it says the Security certificate is expired and upon clicking Advanced and then clicking the unsafe link I am redirected to the page below.

![image](https://github.com/user-attachments/assets/f9916b62-9287-425b-b940-1b92122c4eef)

**Comment by a-ainamdar** [comment]
Hi Hashir,
Can you please contact service provider. They will be able to help you with this.
